/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as JogarRouteImport } from './routes/jogar'
import { Route as EscolherNivelRouteImport } from './routes/escolher-nivel'
import { Route as DivisaoTreinoRouteImport } from './routes/divisao-treino'
import { Route as DivisaoJogarRouteImport } from './routes/divisao-jogar'
import { Route as DivisaoRouteImport } from './routes/divisao'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as IndexRouteImport } from './routes/index'

const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const JogarRoute = JogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolherNivelRoute = EscolherNivelRouteImport.update({
  id: '/escolher-nivel',
  path: '/escolher-nivel',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisaoTreinoRoute = DivisaoTreinoRouteImport.update({
  id: '/divisao-treino',
  path: '/divisao-treino',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisaoJogarRoute = DivisaoJogarRouteImport.update({
  id: '/divisao-jogar',
  path: '/divisao-jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisaoRoute = DivisaoRouteImport.update({
  id: '/divisao',
  path: '/divisao',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/divisao': typeof DivisaoRoute
  '/divisao-jogar': typeof DivisaoJogarRoute
  '/divisao-treino': typeof DivisaoTreinoRoute
  '/escolher-nivel': typeof EscolherNivelRoute
  '/jogar': typeof JogarRoute
  '/professor': typeof ProfessorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/divisao': typeof DivisaoRoute
  '/divisao-jogar': typeof DivisaoJogarRoute
  '/divisao-treino': typeof DivisaoTreinoRoute
  '/escolher-nivel': typeof EscolherNivelRoute
  '/jogar': typeof JogarRoute
  '/professor': typeof ProfessorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/divisao': typeof DivisaoRoute
  '/divisao-jogar': typeof DivisaoJogarRoute
  '/divisao-treino': typeof DivisaoTreinoRoute
  '/escolher-nivel': typeof EscolherNivelRoute
  '/jogar': typeof JogarRoute
  '/professor': typeof ProfessorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/divisao'
    | '/divisao-jogar'
    | '/divisao-treino'
    | '/escolher-nivel'
    | '/jogar'
    | '/professor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aluno'
    | '/divisao'
    | '/divisao-jogar'
    | '/divisao-treino'
    | '/escolher-nivel'
    | '/jogar'
    | '/professor'
  id:
    | '__root__'
    | '/'
    | '/aluno'
    | '/divisao'
    | '/divisao-jogar'
    | '/divisao-treino'
    | '/escolher-nivel'
    | '/jogar'
    | '/professor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunoRoute: typeof AlunoRoute
  DivisaoRoute: typeof DivisaoRoute
  DivisaoJogarRoute: typeof DivisaoJogarRoute
  DivisaoTreinoRoute: typeof DivisaoTreinoRoute
  EscolherNivelRoute: typeof EscolherNivelRoute
  JogarRoute: typeof JogarRoute
  ProfessorRoute: typeof ProfessorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogar': {
      id: '/jogar'
      path: '/jogar'
      fullPath: '/jogar'
      preLoaderRoute: typeof JogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolher-nivel': {
      id: '/escolher-nivel'
      path: '/escolher-nivel'
      fullPath: '/escolher-nivel'
      preLoaderRoute: typeof EscolherNivelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisao-treino': {
      id: '/divisao-treino'
      path: '/divisao-treino'
      fullPath: '/divisao-treino'
      preLoaderRoute: typeof DivisaoTreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisao-jogar': {
      id: '/divisao-jogar'
      path: '/divisao-jogar'
      fullPath: '/divisao-jogar'
      preLoaderRoute: typeof DivisaoJogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisao': {
      id: '/divisao'
      path: '/divisao'
      fullPath: '/divisao'
      preLoaderRoute: typeof DivisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunoRoute: AlunoRoute,
  DivisaoRoute: DivisaoRoute,
  DivisaoJogarRoute: DivisaoJogarRoute,
  DivisaoTreinoRoute: DivisaoTreinoRoute,
  EscolherNivelRoute: EscolherNivelRoute,
  JogarRoute: JogarRoute,
  ProfessorRoute: ProfessorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
